### ISSUE TITLE
sample scripts do not find firewire device

### ISSUE THREAD

**Issue by quietpinguin** [takaswie/libhinawa#1]
Hi Takashi

I have a Focusrite Saffire PRO 24 which works perfectly with snd-firewire-improve.

I have built and installed libhinawa, no problem.

When I run the scripts, for example using "$ python qt5" or going up one level "$ ./samples/run.sh qt5" the script returns: No sound FireWire devices found.

How to fault find?

Cheers, Simon

**Comment by takaswie** [comment]
Yep. It's a bug in UnitQuery object.

Today I released v0.5.0 to obsolete alsa-lib dependency, thus this object is no longer available. Alternatively, SndDice object can open with a fullpath of special file for ALSA hwdep character device. Please refer to renewed samples.

Regards

**Comment by quietpinguin** [comment]
Hi Takashi

I an having troublr building 0.5.0, here is the build log:

$ makepkg -s PKGBUILD
/etc/makepkg.conf: line 117: placed: command not found
==> Making package: libhinawa 0.5.0-0 (So 15. Feb 09:17:09 CET 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found libhinawa-0.5.0.tar.xz
==> Validating source files with md5sums...
    libhinawa-0.5.0.tar.xz ... Passed
==> Extracting sources...
  -> Extracting libhinawa-0.5.0.tar.xz with bsdtar
==> Starting prepare()...
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:38: installing 'config/compile'
configure.ac:38: installing 'config/config.guess'
configure.ac:38: installing 'config/config.sub'
configure.ac:30: installing 'config/install-sh'
configure.ac:30: installing 'config/missing'
Makefile.am: installing './INSTALL'
src/Makefile.am: installing 'config/depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.32.4... yes (version 2.42.1)
checking for gtk-doc... yes
checking for gtkdoc-check... gtkdoc-check.test
checking for gtkdoc-check... /usr/bin/gtkdoc-check
checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... yes
checking for GTKDOC_DEPS... yes
checking for gobject-introspection... yes
checking for ALSA CFLAGS... 
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread
checking for libasound headers version >= 1.0.28... found.
checking for snd_ctl_open in -lasound... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating doc/reference/Makefile
config.status: creating doc/reference/version.xml
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make  all-recursive
make[1]: Entering directory '/home/simon/Build/sources/src/libhinawa-0.5.0'
Making all in src
make[2]: Entering directory '/home/simon/Build/sources/src/libhinawa-0.5.0/src'
  CC       hinawa_context.lo
  GEN      hinawa_sigs_marshal.list
  GEN      hinawa_sigs_marshal.h
  GEN      hinawa_sigs_marshal.c
  CC       hinawa_sigs_marshal.lo
  CC       fw_unit.lo
  CC       fw_resp.lo
  CC       fw_req.lo
  CC       fw_fcp.lo
  CC       snd_unit.lo
snd_unit.c: In function ‘snd_unit_get_property’:
snd_unit.c:92:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     GUINT64_FROM_BE(*((guint64 *)priv->info.guid)));
     ^
  CC       snd_dice.lo
  CC       snd_efw.lo
  CCLD     libhinawa.la
  GISCAN   Hinawa-1.0.gir
  GICOMP   Hinawa-1.0.gir
make[2]: Leaving directory '/home/simon/Build/sources/src/libhinawa-0.5.0/src'
Making all in doc
make[2]: Entering directory '/home/simon/Build/sources/src/libhinawa-0.5.0/doc'
Making all in reference
make[3]: Entering directory '/home/simon/Build/sources/src/libhinawa-0.5.0/doc/reference'
  DOC   Preparing build
  DOC   Scanning header files
  DOC   Introspecting gobjects
  DOC   Rebuilding template files
  DOC   Building XML
./tmpl/backport.sgml:53: warning: Field descriptions for struct snd_efw_transaction are missing in source code comment block.
./tmpl/backport.sgml:66: warning: Field descriptions for struct snd_firewire_event_efw_response are missing in source code comment block.
../../src/snd_dice.c:86: warning: Parameter described in source code comment block but does not exist. FUNCTION: hinawa_snd_dice_open Parameter: Returns.
../../src/snd_efw.c:106: warning: Parameter described in source code comment block but does not exist. FUNCTION: hinawa_snd_efw_open Parameter: Returns.
../../src/snd_unit.c:206: warning: Parameter described in source code comment block but does not exist. FUNCTION: hinawa_snd_unit_open Parameter: Returns.
  DOC   Building HTML
warning: failed to load external entity "../xml/unit_query.xml"
../hinawa-docs.sgml:40: element include: XInclude error : could not load ../xml/unit_query.xml, and no fallback was found
Makefile:693: recipe for target 'html-build.stamp' failed
make[3]: *** [html-build.stamp] Error 6
make[3]: Leaving directory '/home/simon/Build/sources/src/libhinawa-0.5.0/doc/reference'
Makefile:432: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/simon/Build/sources/src/libhinawa-0.5.0/doc'
Makefile:431: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/simon/Build/sources/src/libhinawa-0.5.0'
Makefile:363: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
$ 

Best regards, Simon

**Comment by takaswie** [comment]
> DOC Building HTML
> warning: failed to load external entity "../xml/unit_query.xml"
> ../hinawa-docs.sgml:40: element include: XInclude error : could not load ../xml/unit_query.xml, and no fallback was found
> Makefile:693: recipe for target 'html-build.stamp' failed
> make[3]: ** [html-build.stamp] Error 6

Oops. I forgot to remove an entry from gtk-doc template...

Fix released.
https://github.com/takaswie/libhinawa/commit/b76d7392a7b9e6b8d8dc242388516f8c7424f9bc

**Comment by quietpinguin** [comment]
Hi Takashi

Thanks for the prompt fix. Build is now OK and the sample code for qt5 works (see below).

Next  step is to work out how to read the currrent Focusrite Saffire PRO 24 configuration: e.g. sample rate (44.1/48.0/88.2/96.0), whether playback channels 7 and 8 are from spdif or adat, whether data is streaming, router settings, gain setting of analogue inputs 1 and 2 (lo/hi), etc..

Any ideas? Best regards, Simon

$ ./samples/run.sh qt5
Sound device info:
 type:  1
 card:  0
 device:        fw1
 GUID:  00130e0401c07336
 listening:     True
Dice Notification: 00000020
delete application object
delete snd_unit object
delete fw_resp object
delete fw_req object
$

**Comment by takaswie** [comment]
> Any ideas?

Try reading, and get understood Dice general interface:
http://git.kernel.org/cgit/linux/kernel/git/tiwai/sound.git/tree/sound/firewire/dice/dice-interface.h

Regards
