### ISSUE TITLE
Debian ITP

### ISSUE THREAD

**Issue by kenhys** [takaswie/libhinawa#25]
Let's try to discuss about Intent To Package.

* Wait until 0.7.0 release because of lisence issue.

**Comment by takaswie** [comment]
Here, I describe for what we've already discussed.

1.Where source upstream should be.
 * Q (takaswie): Currently in github.com, but near future I'll push it to alsa-project.org.
    Then upstream is changed. Should we wait for it, then ITP?
 * A (kenhys): No need to wait for it. When upstream changes, I just change package description.

2. The timing of ITP.
 * According to release schedule of Xenial Xerus, Debian import freeze at 18 Feb. When we hope to sync request in Ubuntu project, we need to finish our ITP in the beginning of Feb, at least.
   * https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule
 * TODO (takaswie): find a person who can post sync request to Ubuntu project

3. The interval between ITP and approval
 * Q (takaswie): How long it takes between ITP and approval, usually?
 * A (henrich): depending on FTP master. I know a case to wait for 3 months.

**Comment by takaswie** [comment]
I posted to alsa-devel about 0.7.0 release and ITP.
http://mailman.alsa-project.org/pipermail/alsa-devel/2016-January/103694.html

Let's go ahead.

**Comment by kenhys** [comment]
Confirmed there is no one to do yet:

https://www.debian.org/devel/wnpp/being_packaged
https://www.debian.org/devel/wnpp/requested

**Comment by kenhys** [comment]
ITP: libhinawa is numbered as debian bugs #813474.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813474

**Comment by kenhys** [comment]
also filed RFS here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813489

**Comment by takaswie** [comment]
GJ!

**Comment by kenhys** [comment]
So, there are some phases left:

1. find sponsor (NOW)
2. need to pass sponsor's review
3. fix package & upload to mentors again and again if it needs
4. upload to new queue by sponsor
5. ftp-master checks it. (maybe 3 months later)
6. if rejected by ftp-master, goto step 3.
6. ftp-master upload package into unstable.

**Comment by kenhys** [comment]
libhinawa package is uploaded into debian new queue.
https://ftp-master.debian.org/new.html

wait until ftp-master checks it.

I'll close this issue.
