### ISSUE TITLE
Licensing issue (including GPLv2 file from Linux kernel source)

### ISSUE THREAD

**Issue by takaswie** [takaswie/libhinawa#26]
Currently libhinawa will be shipped under LGPL v2.1, while backport.h comes from Linux kernel userspace application programming interface (UAPI) header and is licensed under GPL v2. (see include/uapi/sound/firewire.h in Linux kernel source.)

Furthermore, this library depends on GLib and GObject, thus runtimes are linked to them automatically. They are licensed under GPL v2. In this case, even if libhinawa is licensed under LGPL v2.1, userspace applications of libhinawa should be licensed under GPL v2. As a result, it seems to have no effectives that libhinawa is licensed under LGPLv2.

Totally, I think it better to change licensing for libhinawa to GPLv2.

**Comment by takaswie** [comment]
I misunderstand. Both of GLib and GObject is license under LGPL
https://git.gnome.org/browse/glib/tree/COPYING

So our issue is just two portions:
 * the usage of Linux UAPI header
 * the inclusion of the header for backport purpose

**Comment by takaswie** [comment]
For issue 1., I refer to a post by Richard Matthew Stallman, Jan 2003 in LKML.
http://lkml.iu.edu/hypermail/linux/kernel/0301.1/0362.html

As long as he said, I think it OK to give LGPL to this library, because it's recognized not to be a derivative work of Linux kernel.

**Comment by takaswie** [comment]
For issue 2., I have a problem. In system with Linux 4.3 or before, without the backport.h (Linux UAPI header), gi-scan fails at building due to a lack of hinawa_snd_dg00x_get_type. Documentation by gtk-doc also fails.

This is a list of introduced symbols to include/uapi/sound/firewire.h:
3.13: DICE
3.16: BEBOB/FIREWORKS
3.19: OXFW
4.4: DIGI00X/TASCAM

I'll save my effort for package optimization to local environment. Currently I realize it reasonable to include the backport.h to this distribution.

**Comment by takaswie** [comment]
Currently I have no way to drop the backport.h. We should add a description about debian/copyright.

**Comment by kenhys** [comment]
> We should add a description about debian/copyright.

You mean that including Linux UAPI header file is not regarded as derivative work, so libhinawa will be distributed under LGPLv2, but we should mention the fact in debian/copyright (GPLv2), doesn't it?

**Comment by takaswie** [comment]
> You mean that including Linux UAPI header file is not regarded as derivative work, 

Yep. Using macros and symbols in GPLv2 code is allowed in LGPLv2.1 code.

> so libhinawa will be distributed under LGPLv2, but we should mention the fact in debian/copyright (GPLv2), doesn't it?

For backport.h. I assume to use the similar fashion as ffmpeg package includes.
http://metadata.ftp-master.debian.org/changelogs/main/f/ffmpeg/ffmpeg_2.8.5-1_copyright

So, backport.h is GPLv2. But the others are under LGPL2.1. Clear?

**Comment by kenhys** [comment]
Thanks! It makes clear.
