### ISSUE TITLE
Change versioning scheme for library interface to libtool.

### ISSUE THREAD

**Issue by takaswie** [takaswie/libhinawa#51]
I maintain versioning of this package by a scheme below:

```
package version = major.minor.micro
```

so that:
 * `major`: updated when losing backward compatibility.
 * `minor`: updated when any new object or property for gobject are added.
 * `micro`: updated when any changes of code except for the above; e.g. bug fixes.

In libtool fashion, versioning of library interface is decided by [this scheme](//www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html). Practically, [this guideline](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) is suggested. The version is described with three parts:

```
iface version = current:revision:age
```

so that:

 * `current`: `The most recent interface number that this library implements. `
 * `revision`: `The implementation number of the current interface.`
 * `age`: `The difference between the newest and oldest interfaces that this library implements.`

Then, at present, I maintain versioning of library interface for libtool by a scheme below:

```
iface version = (minor * 10 + micro):(major):(minor * 10 + micro)
```

The relationship between versions of package/iface/binary is described in this fugure:

version | iface     | .so.x.x.x
------- | ----------| ------
0.3.0   | 30:0:30   | 0.30.0
0.4.0   | 41:0:41   | 0.41.0
0.5.0   | 52:0:52   | 0.52.0
0.6.0   | 63:0:63   | 0.63.0
0.7.0   | 74:0:74   | 0.74.0
0.8.0   | 85:0:85   | 0.85.0
0.8.1   | 81:0:81   | 0.81.0
0.8.2   | 82:0:82   | 0.82.0

For our information, suffix of binary file might be decided by libtool according to this formula:

```
.so.x.y.z = .so.(current - age).(age).(revision)
```

Well, at present, I have a plan to add changes with loss of backward compatibility and I'm working for updating major version to 1. Then, according to my formula, the relationship is described in this fugure:

version | iface     | .so.x.x.x
------- | ----------| ------
1.0.0   | 0:1:0     | 0.0.1

The current field of iface version declines to zero. This loses convention of library interface because the value of current field should be increased monotonically. I need to fix it.

**Comment by takaswie** [comment]
In my opinion, I should change my rule to maintain version of interface with a formula below:

```
iface version = (major * 100 + minor):(minor):(minor)
```

A fundamental concept of this rule is based on `generation`, which means that the minimum version of interface on which binary can kept backward compatibility in a point of interface. This is calcurated by `(major * 100)`.

Under this concept:
 * The `current` field represents current version of the interface (`generation` + `minor`).
 * The `revision` field represents updates within current generation for interface-level compatibility (=`minor`).
 * The 'age' field represents that binary-level compatibility is kept within current generation (=`minor`).

version | iface     | .so.x.x.x
------- | --------- | -------
1.0.0   | 100:0:0   | 100.0.0
1.2.0   | 102:2:2   | 100.2.2
1.3.0   | 103:3:3   | 100.3.3

The reason for multiples of hundred to value of `current` field is with enough consideration about suffix of binary file. It has a calculation with `current` and `revision`. As a result, I have a restriction that the value of `minor` can be allowed up to 99, however I can keep backward compatibility to my old versioning rule.

**Comment by takaswie** [comment]
A topic/iface-v0.1.0 branch includes series of commit for this issue.

**Comment by kenhys** [comment]
It seems that it is preferable libhinawa-1.0.0.tar.gz instead of libhinawa1-1.0.0.tar.gz because there is no need to fix uscan.

**Comment by ML-TakashiSAKAMOTO** [comment]
> It seems that it is preferable libhinawa-1.0.0.tar.gz instead of libhinawa1-1.0.0.tar.gz because there is no need to fix uscan.

@kenhys Okay. I push a commit dd9b522 ('autotools: keep package name and change name of directories') for this purpose. Would you please check it? If it's good, I respin patches in topic/iface-v1.0.0.

**Comment by takaswie** [comment]
It seems that it is preferable libhinawa-1.0.0.tar.gz instead of libhinawa1-1.0.0.tar.gz because there is no need to fix uscan.

@kenhys Okay. I push a commit dd9b522 ('autotools: keep package name and change name of directories') for this purpose. Would you please check it? If it's good, I respin patches in topic/iface-v1.0.0.

**Comment by takaswie** [comment]
For v1.0.0 release, I switched to use Meson instead of GNU Autotools. As a result, no need to care of interface version on libtool fashion. I can use package version as library real-name. In detail, please read 19a61f7e1a18 (' meson: change versioning rule of library interface').

**Comment by takaswie** [comment]
I prepare a topic branch to aggregate all of issues against v1.0.0 release.
https://github.com/takaswie/libhinawa/tree/topic/iface-v1.0.0

**Comment by takaswie** [comment]
Merged to master.
