### ISSUE TITLE
Split debian/* maintainance to salsa.d.o

### ISSUE THREAD

**Issue by kenhys** [takaswie/libhinawa#54]
# Suggestion

I'm planning about moving maintainance under salsa.d.o. [1]
Salsa is a service instance of gitlab.
After migration, libhinawa debian package will be maintained at https://salsa.debian.org/debian/libhinawa.
[1] https://wiki.debian.org/Salsa

# Comparison

Pros.
* upstream (github/libhinawa) need not to care how to maintain debian packages (Sure, you can maintain and coordinate package with )
* other DD also may be able to maintain libhinawa because DD can access to salsa.d.o/debian/libhinawa by default.

Cons.
* repository is split into two parts. mainline and debian specific one.
* need to create salsa.d.o account to contribute debian package. (if contributor is not DD)

# Migration 

upstream ( @takaswie ):
* just remove debian/*. It's all.

maintainer( @kenhys ):
* create repository for libhinawa debian package
* move it to salsa.d.o (ask DD to import that one)
* hack package under salsa.d.o, do regular maintainance task

Any thourght? @takaswie

**Comment by takaswie** [comment]
@kenhys 

> For my information, please tell me your plan to work for this direction; i.e. have you already prepared for it?

Oh, I should have requested `your working schedule` instead of `your plan` because I have a plan to make a release of v0.9.0. In detail, please see a corresponding milestone[1].

[1] https://github.com/takaswie/libhinawa/milestone/3.

**Comment by kenhys** [comment]
salsa.d.o migration task doesn't affect v0.9.0 release because I will work on v0.8.2-1 based one at first.
I mean:
* ask @henrich  to import repository to salsa.d.o ( @kenhys: done)
* release 0.8.2-2, bump debhelper version to 11, compat level 11 and so on. ( @kenhys: not yet)
* after v0.9.0 has been released, I'll work on it. ( @kenhys: not yet)

**Comment by kenhys** [comment]
Moved to https://salsa.debian.org/debian/libhinawa. Done!

**Comment by kenhys** [comment]
I'll prepared 0.8.2-2.
https://salsa.debian.org/debian/libhinawa/commit/380e7a2d4348d5c1441717d96f45f7240be913a7

**Comment by kenhys** [comment]
I've filed 0.8.2-2.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891843

**Comment by takaswie** [comment]
@kenhys Thanks.

I'm waiting for getting sponsors to publish the 0.8.2-2 deb package, then remove deb stuffs from tree for next v0.9.0 release.

**Comment by takaswie** [comment]
@kenhys This morning, I receive two e-mails; one notes v0.8.2-2 was sponsord and another notes it's accepted to unstable.

Thanks for your contribution ;)

**Comment by kenhys** [comment]
I'll close this isssue because of salsa.d.o migration task has finished. Thanks.

**Comment by takaswie** [comment]
Accepted libhinawa 0.8.2-2 (source) into unstable
https://tracker.debian.org/news/940374/accepted-libhinawa-082-2-source-into-unstable/

Thanks for all.

**Comment by takaswie** [comment]
I removed all debian stuffs at a commit ab2f39ad77e7 (' debian: move to salsa.debian.org').
