### ISSUE TITLE
Port to meson for build system

### ISSUE THREAD

**Issue by takaswie** [takaswie/libhinawa#55]
Meson is a build system recently developed for better velocity of build processing.
http://mesonbuild.com/

I prepare for [topic/meson-build branch](https://github.com/takaswie/libhinawa/tree/topic/meson-build) and compare time to build for two cases.

With GNU autotools:
```
$ cat autotools.sh
#!/bin/bash

cd /tmp
git clone ~/git/libhinawa
cd libhinawa
./autogen.sh
./configure --enable-gtk-doc --prefix=/tmp/test
make -j10
make install
```

With meson:
```
$ cat meson.sh
#!/bin/bash

cd /tmp
git clone ~/git/libhinawa
cd libhinawa
meson -Dgtk_doc=true --prefix=/tmp/test . build
cd build
ninja
ninja install
```

As a result:

```
$ time ./autotools.sh
...
real	0m11.922s
user	0m12.955s
sys	0m1.294s
```

```
$ time ./meson.sh
...
real	0m2.035s
user	0m2.447s
sys	0m0.402s
```

Oh, fast.

**Comment by kenhys** [comment]
The point of view in Debian packaging side:

* debhelper supports meson build by default
* It needs to fix `debian/rules` to support a bit.
* no need to remove autotool's stuff from release tar.gz

Thus, switching to `meson-build` branch doesn't make debian packaging task hard.

**Comment by takaswie** [comment]
After investigating a conventional scheme to name library, I concluded that I have no need to care of interface versioning for libtool on Meson. Thus, libhinawa v1.0.0 is released without changing its packaging name to 'libhinawa1'. In detail, see 19a61f7e1a18 (' meson: change versioning rule of library interface').

**Comment by takaswie** [comment]
I prepare a topic branch to aggregate all of issues against v1.0.0 release.
https://github.com/takaswie/libhinawa/tree/topic/iface-v1.0.0

**Comment by takaswie** [comment]
I merged commits for this issue. Stuffs for GNU Autotools remains but will be obsoleted near future.

**Comment by takaswie** [comment]
I decided to obsolete stuffs with GNU autotools at a commit df2ab3c2cfa1.
